//! This file is where the syllabogram translations are accessed.
//!
//! The KANA_TO_ROMANJI map is generated by the build.rs script and stored
//! within the included kana_to_romanji_codegen.rs file.
include!("kana_to_romanji_codegen.rs");  // KANA_TO_ROMANJI

#[derive(PartialEq)]
pub struct KanaTranslation {
    pub kana: &'static str,
    pub romanji: &'static str,
    pub alt_romanji: Option<&'static str>,
}

pub fn get_translations(kana: &[String]) -> Vec<&'static KanaTranslation> {
    kana.iter()
        .map(|k| KANA_TO_ROMANJI.get(k)
            .unwrap_or_else(|| panic!("kana not found: {}", k))
        ).collect()
}
